version: '3.9'

services:
  app:
    container_name: cmsapp
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .db.sqlite3:/code/db.sqlite3

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/code/prometheus/
    ports:
      - "9090:9090"